# Generated by Django 3.2.6 on 2021-08-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_description', models.TextField(max_length=500)),
                ('post_photo', models.ImageField(upload_to='blog/media')),
                ('post_url', models.URLField(blank=True)),
                ('post_data', models.DateField()),
            ],
        ),
    ]
