# Generated by Django 3.2.6 on 2021-08-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='post_data',
            new_name='post_date',
        ),
    ]
