# Generated by Django 3.2.6 on 2021-08-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_photo',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(max_length=20),
        ),
    ]
